-- DDL ( DATA DEFINATION LANGUAGE )

-- CREATE 
CREATE TABLE EMP01(
	P01F01 INT COMMENT "EmpID" PRIMARY KEY AUTO_INCREMENT,
    P01F02 NVARCHAR(50) COMMENT "EmpName",
    P01F03 BIGINT COMMENT "PhoneNumber",
    P01f04 INT COMMENT "IFSC"
);

-- TRUNCATE
TRUNCATE TABLE EMP01;

-- add column in table 
ALTER TABLE 
	EMP01 
ADD COLUMN 
	P01F05 INT COMMENT "Salary";

-- rename table name
ALTER TABLE 
	EMP01
RENAME TO 
	EMP02;

-- DROP
DROP TABLE EMP01;

