-- UNION OF BANK NAMES AND BRANCH NAMES (DISTINCT)
SELECT K01F02 as Name FROM BNK01
UNION
SELECT C01F02 as Name FROM BRC01;

-- UNION ALL OF BANK NAMES AND BRANCH NAMES (ALL, INCLUDING DUPLICATES)
SELECT K01F02 as Name FROM BNK01
UNION ALL
SELECT C01F02 as Name FROM BRC01;
